version: '3.8'
services:
  web:
    build: .
    expose:
      - 5000
    command: gunicorn -b 0.0.0.0:5000 fcompany:app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

networks:
  default:
    name: flask-network
