version: '3.8'
services:
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=fcompany
      - DB_USER=postgres
      - DB_PASSWORD=elena
    expose:
      - 5000
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=fcompany
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elena
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dump_fcompany_pg.sql:/docker-entrypoint-initdb.d/dump_fcompany_pg.sql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  default:
    name: flask-network
