version: '3.8'
services:
  web:
    build: .
    volumes:
      - ./sq_db.sql:/app/sq_db.sql
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=fcompany
      - DB_USER=postgres
      - DB_PASSWORD=elena
    expose:
      - 5000

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=fcompany
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elena
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sq_db.sql:/docker-entrypoint-initdb.d/sq_db.sql

volumes:
  postgres_data:

networks:
  default:
    name: flask-network